import pandas as pd
import json

def generate_html_report(df, output_path="report.html"):
    """Generates a comprehensive HTML report from the results DataFrame with interactive charts."""
    
    # Prepare data for charts
    # 1. bRo5 Status Distribution
    if 'bRo5_Status' in df.columns:
        status_counts = df['bRo5_Status'].value_counts().to_dict()
    else:
        status_counts = {}
        
    # 2. MW vs LogP (Chemical Space)
    scatter_data = []
    if 'MW' in df.columns and 'LogP' in df.columns:
        for _, row in df.iterrows():
            scatter_data.append({
                'x': row['MW'],
                'y': row['LogP'],
                'name': row.get('SMILES', '')[:20] + '...',
                'status': row.get('bRo5_Status', 'Unknown')
            })

    # Basic styling & Scripts
    html_string = f"""
    <html>
    <head>
        <title>Analysis Report</title>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f4f4f9; }}
            .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 20px; box-shadow: 0 0 10px rgba(0,0,0,0.1); border-radius: 8px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
            h2 {{ color: #34495e; margin-top: 30px; }}
            .stats-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }}
            .chart-box {{ border: 1px solid #eee; padding: 10px; border-radius: 4px; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 20px; font-size: 14px; }}
            th, td {{ border: 1px solid #ddd; padding: 12px 8px; text-align: left; }}
            th {{ background-color: #f8f9fa; color: #333; font-weight: 600; }}
            tr:nth-child(even) {{ background-color: #f9f9f9; }}
            tr:hover {{ background-color: #f1f1f1; }}
            .pass {{ color: #27ae60; font-weight: bold; background-color: #eafaf1; padding: 2px 6px; border-radius: 4px; }}
            .fail {{ color: #c0392b; font-weight: bold; background-color: #fdedec; padding: 2px 6px; border-radius: 4px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Comprehensive Analysis Report</h1>
            <p>Generated by LLM Prediction Tool | Total Compounds: {len(df)}</p>
            
            <div class="stats-grid">
                <div class="chart-box">
                    <div id="statusChart"></div>
                </div>
                <div class="chart-box">
                    <div id="chemSpaceChart"></div>
                </div>
            </div>

            <h2>Detailed Results</h2>
            <div style="overflow-x: auto;">
    """
    
    # Convert DataFrame to HTML
    table_html = df.to_html(classes='table', index=False, escape=False)
    
    # Highlight PASS/FAIL
    table_html = table_html.replace('PASS', '<span class="pass">PASS</span>')
    table_html = table_html.replace('FAIL', '<span class="fail">FAIL</span>')
    
    html_string += table_html
    
    # Add Scripts for Charts
    html_string += f"""
            </div>
        </div>
        
        <script>
            // 1. Pie Chart: bRo5 Status
            var statusData = {json.dumps(status_counts)};
            var pieData = [{{
                values: Object.values(statusData),
                labels: Object.keys(statusData),
                type: 'pie',
                marker: {{colors: ['#27ae60', '#c0392b', '#f39c12']}}
            }}];
            var pieLayout = {{
                title: 'bRo5 Compliance Status',
                height: 400
            }};
            Plotly.newPlot('statusChart', pieData, pieLayout);

            // 2. Scatter Plot: Chemical Space (MW vs LogP)
            var rawData = {json.dumps(scatter_data)};
            var trace1 = {{
                x: rawData.map(d => d.x),
                y: rawData.map(d => d.y),
                mode: 'markers',
                type: 'scatter',
                text: rawData.map(d => d.name + '<br>' + d.status),
                marker: {{ 
                    size: 10,
                    color: rawData.map(d => d.status === 'PASS' ? '#27ae60' : '#c0392b'),
                    opacity: 0.7
                }}
            }};
            var scatterLayout = {{
                title: 'Chemical Space (MW vs LogP)',
                xaxis: {{title: 'Molecular Weight (MW)'}},
                yaxis: {{title: 'LogP'}},
                height: 400,
                hovermode: 'closest'
            }};
            Plotly.newPlot('chemSpaceChart', [trace1], scatterLayout);
        </script>
    </body>
    </html>
    """
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_string)
    
    print(f"HTML Report generated at: {output_path}")
        f.write(html_string)
    
    print(f"HTML Report generated at: {output_path}")
